version: '3.5'

services:

#################################### KAFKA BROKER ####################################
  kafka01:
    image: kafka01
    build:
      context: whispeer/
      dockerfile: ./kafka/Dockerfile
#    restart: always
    restart: on-failure
    hostname: kafka01
    container_name: kafka01
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - 9092:9092

    environment:

      LOG_DIR: /home/kafka01/logs
      KAFKA_ADVERTISED_HOST_NAME: kafka01
      KAFKA_LISTENERS: PLAINTEXT://kafka01:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka01:9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper01:2181
 

    depends_on:
      - zookeeper01

  zookeeper01:
    image: zookeeper01
    build:  
      context: whispeer/
      dockerfile: ./zookeeper/Dockerfile
    restart: on-failure
    hostname: zookeeper01
    container_name: zookeeper01
    tty: true
    stdin_open: true
    ports:
      - 2181:2181
    environment:
      LOG_DIR: /home/zookeeper01/logs

